@startuml IeeeDoc_IeeeStandardDocument

'******* CONFIGURATION ************************************************
!include style.uml.inc

'******* CLASS DEFINITION *********************************************
class StandardDocument <<StandardDocument>> {

}

class IeeeStandardDocument {
  +bibdata: IeeeBibliographicItem
  +prefix: IeeePreface
  +sections: ClauseSection[1..*]
  +annex: AnnexSection[0..*]
  +termSources: <<Bibliography>> Citation[0..*]
}

class IeeePreface{
  +foreword: BasicSection
  +introduction: ClauseSection[0..1]
}

class AnnexSection <<StandardDocument>>{

}

class IeeeAnnexSection{
  +appendix: ClauseSection[0..*]
}

'******* NOTES ********************************************************
note "'termSource' points to\nother IEEE Documents where\nthis document inherit their\nTerms and Definition /\nSymbols /\n Abbreviations" as N1

'******* CLASS RELATIONS **********************************************
StandardDocument <|-- IeeeStandardDocument
IeeeStandardDocument <-- IeeePreface

AnnexSection <|-- IeeeAnnexSection

@enduml
